# Generated by Django 6.0.1 on 2026-01-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İHA Adı')),
                ('model_series', models.CharField(max_length=50, verbose_name='Model Serisi')),
                ('weight', models.FloatField(verbose_name='Ağırlık (kg)')),
                ('payload_capacity', models.FloatField(verbose_name='Faydalı Yük Kapasitesi (kg)')),
                ('status', models.CharField(choices=[('Ucusda', 'Uçuşta'), ('Bakimda', 'Bakımda'), ('Hangarda', 'Hangarda')], default='Hangarda', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
