# Generated by Django 6.0.1 on 2026-01-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_category_drone_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Bakım Tarihi'),
        ),
        migrations.AddField(
            model_name='drone',
            name='total_flight_hours',
            field=models.FloatField(default=0, verbose_name='Toplam Uçuş Saati'),
        ),
    ]
