# Generated by Django 5.1.6 on 2026-01-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_drone_last_maintenance_date_drone_total_flight_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='drone',
            options={'verbose_name_plural': "İHA'lar"},
        ),
        migrations.RemoveField(
            model_name='drone',
            name='model_series',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='weight',
        ),
        migrations.AddField(
            model_name='drone',
            name='altitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İrtifa'),
        ),
        migrations.AddField(
            model_name='drone',
            name='endurance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Havada Kalış'),
        ),
        migrations.AddField(
            model_name='drone',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Üretici'),
        ),
        migrations.AddField(
            model_name='drone',
            name='max_takeoff_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Azami Kalkış Ağırlığı (kg)'),
        ),
        migrations.AddField(
            model_name='drone',
            name='range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Menzil / Kontrol'),
        ),
        migrations.AddField(
            model_name='drone',
            name='weapon_capability',
            field=models.TextField(blank=True, null=True, verbose_name='Silah Kabiliyeti'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drones', to='drones.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='payload_capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Faydalı Yük Kapasitesi (kg)'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='status',
            field=models.CharField(choices=[('Hangarda', 'Hangarda'), ('Uçuşta', 'Uçuşta'), ('Bakımda', 'Bakımda'), ('Arızalı', 'Arızalı')], default='Hangarda', max_length=20, verbose_name='Durum'),
        ),
    ]
